using System;
using System.Collections.Generic;
using System.Text;

namespace NWLTLambda.Models
{
    public class ParametersList
    {
        public int CityId { get; set; }
        public string Address { get; set; }
        public string GrowthArea { get; set; }
        public double LotSize { get; set; }
        public double LotLength { get; set; }
        public double LotWidth { get; set; }
        public string SlopeDirection { get; set; }
        public string Zoning { get; set; }
        public string MhaSuffix { get; set; }
        public string Mhaarea { get; set; }
        public double AssessedValue { get; set; }
        public double YearBuilt { get; set; }
        public string HighEndArea { get; set; }
        public string TreeCanopyCoverage { get; set; }
        public double ElevationChange { get; set; }
        public string Alley { get; set; }
        public string CornerLot { get; set; }
        public string MajorArterial { get; set; }
        public string Ecas { get; set; }
        public string WaterMainExtension { get; set; }
        public double WaterMainLength { get; set; }
        public string SewerMainExtension { get; set; }
        public double SewerMainLength { get; set; }
        public string AlleyConstruction { get; set; }
        public double AlleyConstructionLength { get; set; }
        public string DrainageMain { get; set; }
        public double DrainageDistance { get; set; }
        public string UndergroundGarage { get; set; }
        public int NumberOfSpots { get; set; }
        public double FloorAreaRatio { get; set; }
        public double FarMax { get; set; }
        public double Number_of_homes { get; set; }
        public double Aadu { get; set; }
        public double Dadu { get; set; }
        public double SellableSqftFactor { get; set; }
        public double SellableSqFootage { get; set; }
        public double Aadu_size { get; set; }
        public double Dadu_size { get; set; }
        public double BuildingSquareFootage { get; set; }
        public double InefficientSpacePercentage { get; set; }
        public double NumberOfUnits { get; set; }
        public double MinimumLotSize { get; set; }
        public int SfBaseCostPerSqft { get; set; }
        public double TownhomeBaseCostPerSqft { get; set; }
        public double CottageBaseCostPerSqft { get; set; }
        public double RowhouseBaseCostPerSqft { get; set; }
        public double ApartmentBaseCostPerSqft { get; set; }
        public double CondoBaseCostPerSqft { get; set; }
        public double ADUBaseCostPerSqft { get; set; }
        public double SfBaseCost { get; set; }
        public double TownhomeBaseCost { get; set; }
        public double CottageBaseCost { get; set; }
        public double RowhouseBaseCost { get; set; }
        public double ApartmentBaseCost { get; set; }
        public double CondoBaseCost { get; set; }
        public double AADUBaseCost { get; set; }
        public double EcaCost { get; set; }
        public double ColorAreaBuildingCost { get; set; }
        public double Add4StoryCost { get; set; }
        public double CostPerGrade { get; set; }
        public double ElevationGradeCost { get; set; }
        public double WaterLineCostPerSqft { get; set; }
        public double WaterLineCost { get; set; }
        public double AlleyCostPerSqft { get; set; }
        public double SewerCost { get; set; }
        public double SewerCostPerSqft { get; set; }
        public double StormDrainCost { get; set; }
        public double StormDrainCostPerSqft { get; set; }
        public double AlleyCost { get; set; }
        public double UndergroundParkingCostPerStall { get; set; }
        public double UndergroundParkingBaseCost { get; set; }
        public double MhaCost { get; set; }
        public double TotalBuildingCostPerLot { get; set; }
        public double TotalProjectCost { get; set; }
        public double DaduBaseCost { get; set; }
        public double TotalBuildingCostPerUnit { get; set; }
        public double TotalBuildingCostPerHome { get; set; }
        public double ApartmentEstimatedValue { get; set; }
        public double HomeEstimatedValue { get; set; }
        public double SfEstimatedValue { get; set; }
        public double AADUEstimatedValue { get; set; }
        public double DaduEstimatedValue { get; set; }
        public double SalesCommission { get; set; }
        public double ExciseTax { get; set; }
        public double EscrowFees { get; set; }
        public double MarketingAndStaging { get; set; }
        public double MonthlyRentPerUnit { get; set; }
        public double VacancyRate { get; set; }
        public double AnnualRent { get; set; }
        public double YearlyApartmentTaxes { get; set; }
        public double ApartmentCapRate { get; set; }
        public double OperatingExpensesPerFt { get; set; }
        public double OcipPolicy { get; set; }
        public double TotalVacancyAllowance { get; set; }
        public double ApartmentGrossIncome { get; set; }
        public double TotalOperatingExpenses { get; set; }
        public double TotalSalesCostPerLot { get; set; }
        public double TotalSalesCostPerHome { get; set; }
        public double TotalSalesCostPerUnit { get; set; }
        public double TotalSalesCostPerProject { get; set; }
        public double UnitEstimatedValue { get; set; }
        public double LotEstimatedValue { get; set; }
        public double NetIncome { get; set; }
        public double LivableSqft { get; set; }
        public double TotalFinancingCostPerHome { get; set; }
        public double ProfitPerHomeBeforeFinancing { get; set; }
        public double TotalNetProfit { get; set; }
        public double ValueofLandPerHome { get; set; }
        public double TotalLandValue { get; set; }
        public double ValueOfLandPerLot { get; set; }
        public double ValueOfLandPerUnit { get; set; }
        public double ProfitPerLotBeforeFinancing { get; set; }
        public double ProfitPerUnitBeforeFinancing { get; set; }
        public double ProfitForProjectBeforeFinancing { get; set; }
        public double NetProfitPerLot { get; set; }
        public double NetProfitPerHome { get; set; }
        public double NetProfitPerUnit { get; set; }
        public double NetProfitForProject { get; set; }
        public double DesiredProfitPercent { get; set; }
        public double DesiredProfitBeforeFinancing { get; set; }
        public double BackendSalesPrice { get; set; }
        public double ValueOfLandPerHome { get; set; }
        public double Equity { get; set; }
        public double AcquisitionCarryingMonths { get; set; }
        public int InterestRateLandAcquisition { get; set; }
        public double TotalFinancingCostLandAcquisition { get; set; }
        public double InterestRateConstructionLoan { get; set; }
        public double LoanFeesConstructionLoan { get; set; }
        public double ConstructionLoanMonths { get; set; }
        public int TotalFinancingCostConstruction { get; set; }
        public double AssignmentFees { get; set; }
        public double MonthsToSellAfterCompletion { get; set; }
        public int ExtraFinancingAfterCompletion { get; set; }
        public double TotalFinancingFees { get; set; }
        public double LoanFeesLandAcquisitionLoan { get; set; }

        public double TotalFinancingCostPerUnit { get; set; }
    }
}
